language: ruby

rvm:
  - 2.3.1

cache:
  - bundler

sudo: required

services:
  - redis
  - docker

env:
  global:
    - secure: "dHEzdRO8UStsuALJEJPT2/0kfaPzmsRwKWtQwjpgr0K+fmWFaHpkaWTeDxORLU5RnQ5MwVWkfQmZRWx1DAHawrc6HJxNj0nxBqnofZiw2lJ90QAL1gZ7XnbRqtjnvmmowdh+BopKJ4CvWErwj9Hs/B4qKHNZhmYP2GQLzCvd8XX6zJ6Hnv4vAdfZQf8Qss9S7r3yMajqcG0oyOOCiQfSWHaai0hFz+nK+071uZZ+c43Z/48ie7l86v0bhSSdOKa8ebOwHI02t/F9diLZDFXeYtuEEybABqvb26zPnFvGDTk6Bx0dE9hXRhcQ8KX7erbQYu4nflIqojgXddtDurtz0hrVpIqb4bdgKRG5WpEyf8SMdIDeNUT6O2EDTWGBSAbE7578v1jwitfRz95ksj21TqrzGpsyZcUhFB9KEqyvcCBGdjAzeEuwD9pB8ElfLKeBcALJNOczoFEPaS5W5t2XzVKOkiuebYQYhocm0P3g3GnYStmgjNXbCY5CYMDSvTACI5ikQCLFgbUZZ0MxKkbukidqplOjkCBFgwNxKHy2YhMCEmZqxDrorGXJbAJuKNm0a2bBAdQrb/6HEPqVYHBFNaoi4rHDGxgVkT3ufAOS5yQsB9YwLnyYiEfyV94xb7jUEhRSPJ4ZUtJWD1fuTvGEmbSdkeaDENCiW4ZXWz5tsbU=" # DOCKER_EMAIL
    - secure: "GFRZh9/q+9oE46gdJk+1s0l///uQZJVBy5LVFEvRPF9k+Hk5IK4g/GH+3jcBP5mufjSnSG4t1G2KZwahP3jbYtHTn9ET5ezFPG5dUmLEyGzZi1oM+2BDhoRctZSykZDwOqNZgdreamAUPj6PTY1dWN0UdiiZJVBe2PkUapvSxpSo9kuy3tLrVed36fUEjOf2knzeYvw8xfB/g8vJ8f8jQ+SQRnjav9H+Ar3MNoOurU8hLQdl1Od+Dn+Jn2ISpWGq5YzO1nLsoKLv20lGDsa5/S5WxEt8DhN67r8uibQ4HhxF2OZ/sNUjBo90sgHi6WehvsAtxV1LRGN+u798Wb9vkbPx15ynrRUszrlyaJh+zetTxbLfzIiRJNU4wVwlfRbQETiV5zunOy/I7DcUXlWgEHq1D4kppOe7ie0JyLiQcO2Vh73cq3GnJhnPGyO5dsVLK7G6I16HoBlnXeGo/75lZ26HuyxeM+mqgHwcCSnKwPWrTe/lEIMGCCPf7xeHjAa1/3j2/BgxTFguKpvajqhWWwsfdF0/fGgOpmDK2JlBo7JASr/YqSiM61zo6KHuCllKeKrxUvOMyHwaabXgu4qcOOAD82Ng5RMGd04uG0qNQskStQlbRX2c/rxTtNCWpQr39iw227fJrfz4sHV6oryUWusC5o9uPjjpvWqbd+uuHo4=" # DOCKER_USER
    - secure: "gMWa0FpJ4riBybJC02TEYmfbCAOzjvdWkpt7CtpKSH9mJJRGVJrA8MWaCa0tjd1dAE6dmfEfQwo8/8uQ0DJ7OgzPdsYvutbD8paV/IYYZx8vuTz3/N0XVZquGeM8WIvlibfZ0PS2vZBghb5wdvS/Y9dxFHKmiLPgnQmv7IoDYRQ9lxClhw4O9hGAvjGhEpY/Nvrzp0yMmC1JqhxjUomPsoW+5yRhucSxNfxnbmRtZ6w1nw6s+W2rKel9rEkBvKaSenyzBABANR+syXJl9T4bGUrzASsXHalpahFwm+9KrndWuFzdhcXFB5fNXFEX8vns34yrvCqfR8+5pbnwJAFheCcY/4Ptb2gG9JTC9mMvJ3qtDZ51ZgK+Gqy4rtlLCYsiPgnaykZhESf2YV1xaotSQ1DbwdnzI0coARS82D1g+rOHIp7+Z1WQsHc1YvzyuLNZVBs/t4vUu9liFfJCxgnGoSPIyZ9KdMX0fpV+99l9KdUrcVj/iVYFlK3OdV7IZnaAWMkewNh2URyTM9ZLb5cnyqffKe6Z+QIJlCzkQgoGsDR7JAh0ksCHyKZ/wh/pB+G6AMZ7D7jr6gcUqtSZIV4sBXV2hwIc4y0lRIXfnwCDEMOma0dS/SW1FIDy5v200g0q9AYsHE5AfTl6b0i3MbICGI9nYiC8WgLj1BODzeHGTH4=" # DOCKER_PASS

addons:
  code_climate:
    repo_token: 6cbd717825168f2013cc629940b106ab49370df3e3916ea15fbfd9fd9182c470

script: bundle exec rspec

after_success:
  - ./script/deploy.sh
